// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfxMaBWqYkL0v4sInDS0N8muW2VO1Sx8',
    appId: '1:111069048624:web:a8c2d13cc644a9c1e9a2f5',
    messagingSenderId: '111069048624',
    projectId: 'miaged-d48f6',
    authDomain: 'miaged-d48f6.firebaseapp.com',
    storageBucket: 'miaged-d48f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDl9ruPhU5NnhatnWJ39_imByv_s6I6Gk',
    appId: '1:111069048624:android:2552962b30cef7b6e9a2f5',
    messagingSenderId: '111069048624',
    projectId: 'miaged-d48f6',
    storageBucket: 'miaged-d48f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpJf3-IU5P_XTsIYx1I_vn_Jf7SgWY_k',
    appId: '1:111069048624:ios:b961af381a9b15b3e9a2f5',
    messagingSenderId: '111069048624',
    projectId: 'miaged-d48f6',
    storageBucket: 'miaged-d48f6.appspot.com',
    iosClientId: '111069048624-q0cmb8m93q5b0o16n698h855r4ghif8i.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWpJf3-IU5P_XTsIYx1I_vn_Jf7SgWY_k',
    appId: '1:111069048624:ios:bfbcf7fc1171db7be9a2f5',
    messagingSenderId: '111069048624',
    projectId: 'miaged-d48f6',
    storageBucket: 'miaged-d48f6.appspot.com',
    iosClientId: '111069048624-lece4mmj5c8su7tmo1j242cuc7cpp9mg.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.miaged.RunnerTests',
  );
}
